sudo: required
language: java
script: mvn org.codehaus.mojo:license-maven-plugin:download-licenses

after_success:  
- curl -X POST --url https://app.leanix.net/services/mtm/v1/oauth2/token -u apitoken:w88vxVddOKs8TfWg2VyGwmx4DpadFKzyxb7adVSk --data grant_type=client_credentials | jq -r '.access_token'
services:
  - docker
