sudo: required
language: java
script: mvn org.codehaus.mojo:license-maven-plugin:download-licenses

after_success:  
- curl -X POST \
    "https://app.leanix.net/services/cicd-connector/v1/dependencies?source=mvn&externalId=123"\
    -H 'content-type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW' \
    -F 'api_token='w88vxVddOKs8TfWg2VyGwmx4DpadFKzyxb7adVSk\
    -F 'host=app.leanix.net' \
    -F 'file=@maven-dependencies.xml'
services:
  - docker
